version: '3'

services:
  web:
    build: .
    command: npm start
    restart: always
    ports:
      - "8080:8080"
    links:
      - mongodb
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    ports: 
      - "27019:27017"

