version: "3.5"

services:
    zoo:
        image: zookeeper
        container_name: zookeeper
        restart: always
        hostname: zoo
        ports:
            - 2181:2181
            - 8080:8080
        networks:
            - zookeeper
        environment:
            ZOO_MY_ID: 1
            ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181

networks:
    zookeeper:
        name: zookeeper_network
        driver: bridge
    
