version: '3'

services:
  orchestrator:
    build: .
    image: orchestrator:latest
#    command: npm start
    restart: always
    ports:
      - "80:8000"
    depends_on:
      - mongodb
    networks: 
      - orchestrator_network
    environment:
      - TEAM_NAME=CC_0276_0652_0706_1808
networks:
  orchestrator_network:
    driver: bridge

