version: '3'

services:
  web:
    build: .
    command: npm start
    restart: always
    ports:
      - "8000:8000"
    links:
      - mongodb
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    ports: 
      - "27018:27017"

