version: "3.5"

services:
    dbworker_master:
        build: .
        image: dbworker_master:latest
        container_name: dbworker_master
        #    command: npm start
        restart: always
        depends_on:
            - mongodb_master
        networks:
            - master_network
            - rabbitmq_network
            - zookeeper_network
        environment:
            - TEAM_NAME=CC_0276_0652_0706_1808
            - ROLE=master
            - DB_HOST=mongodb_master
    mongodb_master:
        image: mongo
        container_name: mongodb_master
        expose:
            - "27017"
        networks:
            - master_network
        environment:
            - TEAM_NAME=CC_0276_0652_0706_1808
networks:
    master_network:
        name: master_network
        driver: bridge
    rabbitmq_network:
        external: true
    zookeeper_network:
        external: true
