version: '3.5'

services:
  dbworker_slave:
    build: .
    image: dbworker_slave:latest
    container_name: dbworker_slave
#    command: npm start
    restart: always
    depends_on:
      - mongodb_slave
    networks: 
      - slave_network
      - rabbitmq_network
      - zookeeper_network
    environment:
      - TEAM_NAME=CC_0276_0652_0706_1808
      - ROLE=slave
      - DB_HOST=mongodb_slave
  mongodb_slave:
    image: mongo
    container_name: mongodb_slave
    expose: 
      - "27017"
    networks:
      - slave_network
    environment:
      - TEAM_NAME=CC_0276_0652_0706_1808
networks:
  slave_network:
    name: slave_network
    driver: bridge
  rabbitmq_network:
    external: true
  zookeeper_network:
    external: true

