version: "3.5"

services:
    dbworker:
        build: .
        image: dbworker:latest
        container_name: master
        restart: always
        networks:
            - rabbitmq_network
        depends_on:
            - mongodb
        environment:
            - TEAM_NAME=CC_0276_0652_0706_1808
    mongodb:
        image: bitnami/mongodb
        container_name: mongo
        environment:
            - TEAM_NAME=CC_0276_0652_0706_1808

networks:
    rabbitmq_network:
        external: true
